version: '3'
services:  
backend:    
build: .    
ports:      
- "8000:8000"
    environment:    
      - GROQ_API_KEY=${GROQ_API_KEY}   
       command: uvicorn app.main:app --host 0.0.0.0 --port 8000
        frontend:    build: .   
         ports:     
          - "8501:8501"   
           depends_on:     
            - backend    
            command: streamlit run frontend/streamlit_app.py